<?php
/**
 * Class which returns the class map definition
 * @package
 */
class ClassMap
{
    /**
     * Returns the mapping between the WSDL Structs and generated Structs' classes
     * This array is sent to the \SoapClient when calling the WS
     * @return string[]
     */
    final public static function get()
    {
        return array(
            'GetTransactionUpdateXml' => '\\StructType\\GetTransactionUpdateXml',
            'GetTransactionUpdateXmlResponse' => '\\StructType\\GetTransactionUpdateXmlResponse',
            'FirstPayResponse' => '\\StructType\\FirstPayResponse',
            'ArrayOfTransaction' => '\\ArrayType\\ArrayOfTransaction',
            'Transaction' => '\\StructType\\Transaction',
            'ArrayOfSuspenseTransaction' => '\\ArrayType\\ArrayOfSuspenseTransaction',
            'SuspenseTransaction' => '\\StructType\\SuspenseTransaction',
            'SubBatch' => '\\StructType\\SubBatch',
            'Batch' => '\\StructType\\Batch',
            'ArrayOfSubBatch' => '\\ArrayType\\ArrayOfSubBatch',
            'Organisation' => '\\StructType\\Organisation',
            'ArrayOfAccount' => '\\ArrayType\\ArrayOfAccount',
            'Account' => '\\StructType\\Account',
            'ArrayOfAccountCard' => '\\ArrayType\\ArrayOfAccountCard',
            'AccountCard' => '\\StructType\\AccountCard',
            'ArrayOfETranzactCard' => '\\ArrayType\\ArrayOfETranzactCard',
            'eTranzactCard' => '\\StructType\\ETranzactCard',
            'Bank' => '\\StructType\\Bank',
            'ArrayOfBankBranch' => '\\ArrayType\\ArrayOfBankBranch',
            'BankBranch' => '\\StructType\\BankBranch',
            'ArrayOfSuspenseAccount' => '\\ArrayType\\ArrayOfSuspenseAccount',
            'SuspenseAccount' => '\\StructType\\SuspenseAccount',
            'CurrencyType' => '\\StructType\\CurrencyType',
            'ArrayOfThirdPartyAccount' => '\\ArrayType\\ArrayOfThirdPartyAccount',
            'ThirdPartyAccount' => '\\StructType\\ThirdPartyAccount',
            'ArrayOfBatch' => '\\ArrayType\\ArrayOfBatch',
            'ArrayOfChannelConfiguration' => '\\ArrayType\\ArrayOfChannelConfiguration',
            'ChannelConfiguration' => '\\StructType\\ChannelConfiguration',
            'ArrayOfFapxOrgHeader' => '\\ArrayType\\ArrayOfFapxOrgHeader',
            'FapxOrgHeader' => '\\StructType\\FapxOrgHeader',
            'FapxHeader' => '\\StructType\\FapxHeader',
            'ArrayOfFileWatcherLog' => '\\ArrayType\\ArrayOfFileWatcherLog',
            'FileWatcherLog' => '\\StructType\\FileWatcherLog',
            'ArrayOfMenuPage' => '\\ArrayType\\ArrayOfMenuPage',
            'MenuPage' => '\\StructType\\MenuPage',
            'ArrayOfRoleMenuPage' => '\\ArrayType\\ArrayOfRoleMenuPage',
            'RoleMenuPage' => '\\StructType\\RoleMenuPage',
            'Role' => '\\StructType\\Role',
            'ArrayOfTranWorkFlowLevelApprover' => '\\ArrayType\\ArrayOfTranWorkFlowLevelApprover',
            'TranWorkFlowLevelApprover' => '\\StructType\\TranWorkFlowLevelApprover',
            'TranWorkFlowLevel' => '\\StructType\\TranWorkFlowLevel',
            'TranWorkflow' => '\\StructType\\TranWorkflow',
            'ArrayOfTransactionApprovalLog' => '\\ArrayType\\ArrayOfTransactionApprovalLog',
            'TransactionApprovalLog' => '\\StructType\\TransactionApprovalLog',
            'ArrayOfTranWorkFlowLevel' => '\\ArrayType\\ArrayOfTranWorkFlowLevel',
            'WorkFlowType' => '\\StructType\\WorkFlowType',
            'ArrayOfTranWorkflow' => '\\ArrayType\\ArrayOfTranWorkflow',
            'ArrayOfWorkFlow' => '\\ArrayType\\ArrayOfWorkFlow',
            'WorkFlow' => '\\StructType\\WorkFlow',
            'ArrayOfWorkflowConfig' => '\\ArrayType\\ArrayOfWorkflowConfig',
            'WorkflowConfig' => '\\StructType\\WorkflowConfig',
            'User' => '\\StructType\\User',
            'ArrayOfOrgRM' => '\\ArrayType\\ArrayOfOrgRM',
            'OrgRM' => '\\StructType\\OrgRM',
            'ArrayOfUserSessionLog' => '\\ArrayType\\ArrayOfUserSessionLog',
            'UserSessionLog' => '\\StructType\\UserSessionLog',
            'ArrayOfWorkFlowTransactionLog' => '\\ArrayType\\ArrayOfWorkFlowTransactionLog',
            'WorkFlowTransactionLog' => '\\StructType\\WorkFlowTransactionLog',
            'WorkFlowTransaction' => '\\StructType\\WorkFlowTransaction',
            'ArrayOfWorkFlowTransaction' => '\\ArrayType\\ArrayOfWorkFlowTransaction',
            'ArrayOfUser' => '\\ArrayType\\ArrayOfUser',
            'Page' => '\\StructType\\Page',
            'ArrayOfRolePage' => '\\ArrayType\\ArrayOfRolePage',
            'RolePage' => '\\StructType\\RolePage',
            'ArrayOfPage' => '\\ArrayType\\ArrayOfPage',
            'ArrayOfOrgChannelCharge' => '\\ArrayType\\ArrayOfOrgChannelCharge',
            'OrgChannelCharge' => '\\StructType\\OrgChannelCharge',
            'ArrayOfRole' => '\\ArrayType\\ArrayOfRole',
            'ArrayOfUpload' => '\\ArrayType\\ArrayOfUpload',
            'Upload' => '\\StructType\\Upload',
            'Pain001Upload' => '\\StructType\\Pain001Upload',
            'ArrayOfAPITransaction' => '\\ArrayType\\ArrayOfAPITransaction',
            'APITransaction' => '\\StructType\\APITransaction',
            'ArrayOfPain001Tran' => '\\ArrayType\\ArrayOfPain001Tran',
            'Pain001Tran' => '\\StructType\\Pain001Tran',
            'xHeader' => '\\StructType\\XHeader',
            'GetTransactionUpdateList' => '\\StructType\\GetTransactionUpdateList',
            'GetTransactionUpdateListResponse' => '\\StructType\\GetTransactionUpdateListResponse',
            'GetTransaction' => '\\StructType\\GetTransaction',
            'GetTransactionResponse' => '\\StructType\\GetTransactionResponse',
            'SendPaymentList' => '\\StructType\\SendPaymentList',
            'ArrayOfPaymentTrans' => '\\ArrayType\\ArrayOfPaymentTrans',
            'PaymentTrans' => '\\StructType\\PaymentTrans',
            'SendPaymentListResponse' => '\\StructType\\SendPaymentListResponse',
            'SendTransactionsList' => '\\StructType\\SendTransactionsList',
            'SendTransactionsListResponse' => '\\StructType\\SendTransactionsListResponse',
            'SendTransaction' => '\\StructType\\SendTransaction',
            'SendTransactionResponse' => '\\StructType\\SendTransactionResponse',
            'SendTransactionsData' => '\\StructType\\SendTransactionsData',
            'TransData' => '\\StructType\\TransData',
            'SendTransactionsDataResponse' => '\\StructType\\SendTransactionsDataResponse',
            'SendTransactionsXml' => '\\StructType\\SendTransactionsXml',
            'SendTransactionsXmlResponse' => '\\StructType\\SendTransactionsXmlResponse',
            'SendTransactionsPostAsBulk' => '\\StructType\\SendTransactionsPostAsBulk',
            'SendTransactionsPostAsBulkResponse' => '\\StructType\\SendTransactionsPostAsBulkResponse',
        );
    }
}
